//Guitar
export const START_TRAIN = 'START_TRAIN';
export const END_TRAIN = 'END_TRAIN';

export const USER_SELECTED_NOTE_START = 'USER_SELECTED_NOTE_START';
export const USER_SELECTED_NOTE_END = 'USER_SELECTED_NOTE_END';
export const USER_INIT_LOAD = 'USER_INIT_LOAD';
export const CHANGE_USER_ANSWER_TIMING = 'CHANGE_GUITAR_ANSWER_TIMING';

export const SEE_ALL_NOTES_ON_NECK = 'SEE_ALL_NOTES_ON_NECK';

export const CHANGE_GUITAR_TYPE = 'CHANGE_GUITAR_TYPE';